#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Apr 10 09:30:16 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=photon_v1.2a (3).zip
enableShaders=true
